import { Book } from './books.object';

export const BOOKS:Book[] = [
  {id:1, title:'I, Robot', author: 'Isaac Azimov', publicationDate: 1950, description: 'Сборник рассказов \n"Я, робот\n" - одно из самых известных произведений классика американской фантастической литературы.', bookCover: 'https://www.100bestbooks.ru/pictures/books/Asimov_I_Robot.jpg'},
  {id:2, title:'The Lord of the Rings', author: 'J. R. R. Tolkien', publicationDate: 1954, description: 'The Lord of the Rings is an epic high fantasy novel by the English author and scholar J. R. R. Tolkien', bookCover: 'https://i.pinimg.com/originals/78/1d/e8/781de8c2946e17feaa4b0aa9dce057d7.jpg'},
  {id:3, title:'Clean Code', author: 'Robert C. Martin', publicationDate: 2009, description: ' A Handbook of Agile Software Craftsmanship', bookCover: 'https://www.todaysoftmag.com/images/articles/tsm29/carteCleanCode.jpg'},
  {id:4, title:'Вы не знаете JS. Замыкания и объекты', author: 'Симпсон К.', publicationDate: 2019, description: 'Каким бы опытом программирования на JavaScript вы ни обладали, скорее всего, вы не понимаете язык в полной мере. Это лаконичное, но при этом глубоко продуманное руководство познакомит вас с областями видимости, замыканиями, ключевым словом this и объектами – концепциями, которые необходимо знать для более эффективного и производительного программирования на JS. Вы узнаете, как и почему они работают, и как замыкания могут стать эффективной частью вашего инструментария разработки. .Как и в других книгах серии «Вы не знаете JS», здесь рассматриваются нетривиальные аспекты языка, от которых программисты JavaScript предпочитают держаться подальше. Вооружившись этими знаниями, вы достигнете истинного мастерства JavaScript.', bookCover: 'https://img-gorod.ru/27/402/2740227_detail.jpg'},
  {id:5, title:'Вы не знаете JS. Асинхронная обработка и оптимизация', author: 'Симпсон К.', publicationDate: 2019, description: 'Каким бы опытом программирования на JavaScript вы ни обладали, скорее всего, вы не понимаете язык в полной мере. Это лаконичное, но при этом глубоко продуманное руководство посвящено новым асинхронным возможностям и средствам повышения производительности, которые позволяют создавать сложные одностраничные веб-приложения и избежать при этом «кошмара обратных вызовов».', bookCover: 'https://img-gorod.ru/27/402/2740224_detail.jpg '},
]
